version: "3"
services:
  bot:
    build: ./expose-finder
    volumes:
      - ./expose-finder:/config
    depends_on:
      - redis
    command: [ "python3", "-u", "flathunt.py", "-c", "/config/config.yaml", "--redis_host", "redis"]
  redis:
    image: redis
