name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./expose-finder
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        pylint `ls -R|grep .py$|xargs`
